# Generated by Django 5.2.8
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.ImageField(upload_to='banners')),
                ('link', models.URLField(blank=True, help_text='URL a la que redirige el banner', null=True)),
                ('posicion', models.CharField(choices=[('principal', 'Banner Principal (Hero)'), ('lateral', 'Banner Lateral'), ('footer', 'Banner Footer')], default='lateral', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número = mayor prioridad)')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['orden', '-fecha_inicio'],
            },
        ),
    ]